// 학습 자료: 만능 문장, 필러, 연결어, 상황별 표현, 고득점 어휘
const STUDY_SECTIONS = [
  {
    id: 'universal',
    name: '만능 문장',
    icon: '🪄',
    desc: '어떤 질문에도 쓸 수 있는 문장들. 시간 벌기 → 본론 → 마무리 흐름을 만들어줘요.',
    items: [
      { text: "That's a really interesting question.", meaning: '시간 벌기 (질문 직후)', example: "Oh, that's a really interesting question. Let me think." },
      { text: 'Well, let me think about that for a second.', meaning: '생각할 시간 벌기', example: "Hmm, well, let me think about that for a second... Okay, so..." },
      { text: 'Oh, where do I even start?', meaning: '할 말이 많다는 뉘앙스로 시작', example: "My favorite movie? Oh, where do I even start?" },
      { text: "It's hard to pick just one, but if I had to choose...", meaning: '하나 고르기 어려울 때', example: "It's hard to pick just one, but if I had to choose, I'd say my trip to Jeju." },
      { text: "To be honest, I've never really thought about that before.", meaning: '돌발 질문 대처', example: "To be honest, I've never really thought about that before, but I guess..." },
      { text: 'If I remember correctly, it was about two years ago.', meaning: '과거 경험 시작', example: 'If I remember correctly, it was about two years ago, in the summer.' },
      { text: 'Looking back on it now, it was such a great experience.', meaning: '경험 회상 마무리', example: 'Looking back on it now, it was such a great experience for me.' },
      { text: "What I'm trying to say is...", meaning: '말이 꼬였을 때 정리', example: "What I'm trying to say is, it totally changed how I see things." },
      { text: "All in all, that's why I really enjoy it.", meaning: '이유 설명 마무리', example: "All in all, that's why I really enjoy going there every weekend." },
      { text: "So yeah, that's pretty much it.", meaning: '자연스러운 답변 마무리', example: "So yeah, that's pretty much it. That's my typical weekend." },
    ],
  },
  {
    id: 'fillers',
    name: '필러 · 담화표지',
    icon: '🧩',
    desc: '침묵 대신 자연스럽게 채우는 말들. 남발하지 말고 문장 사이사이에 양념처럼!',
    items: [
      { text: 'you know', meaning: '있잖아요 (공감 유도)', example: "It was, you know, one of those days when everything goes wrong." },
      { text: 'actually', meaning: '사실은 (정보 수정·강조)', example: "Actually, I didn't like coffee at first." },
      { text: 'I mean', meaning: '그러니까 내 말은 (부연)', example: "It was huge. I mean, it took us an hour to walk around it." },
      { text: 'kind of / sort of', meaning: '약간, 어느 정도 (완화)', example: "I was kind of nervous at first, but it turned out fine." },
      { text: 'well', meaning: '음, 글쎄 (뜸들이기)', example: "Well, it depends on the situation, I guess." },
      { text: 'to be honest', meaning: '솔직히 말하면', example: "To be honest, I'm not a big fan of horror movies." },
      { text: 'the thing is', meaning: '문제는, 중요한 건', example: "I wanted to go, but the thing is, I had no time at all." },
      { text: 'as far as I know', meaning: '내가 알기로는', example: "As far as I know, it's the oldest cafe in my neighborhood." },
      { text: 'believe it or not', meaning: '믿기 힘들겠지만', example: "Believe it or not, I've watched that movie more than ten times." },
      { text: 'if that makes sense', meaning: '무슨 말인지 아시겠죠? (마무리)', example: "It's busy but relaxing at the same time, if that makes sense." },
    ],
  },
  {
    id: 'connectors',
    name: '연결어',
    icon: '🔗',
    desc: '문장과 문장을 잇는 다리. 스토리에 흐름과 논리를 만들어줘요.',
    items: [
      { text: 'first of all', meaning: '우선, 먼저', example: 'First of all, the location is perfect for me.' },
      { text: 'on top of that', meaning: '게다가 (추가)', example: "The food was amazing, and on top of that, the staff were super friendly." },
      { text: 'speaking of which', meaning: '말이 나온 김에', example: "Speaking of which, I actually went there again last weekend." },
      { text: 'meanwhile', meaning: '그러는 동안', example: 'I was waiting in line. Meanwhile, my friend was looking for seats.' },
      { text: 'whereas', meaning: '~인 반면 (비교)', example: 'My hometown is quiet, whereas Seoul is always crowded and busy.' },
      { text: 'even though', meaning: '~임에도 불구하고', example: 'Even though it was raining, we decided to go hiking anyway.' },
      { text: 'as a result', meaning: '그 결과', example: 'I practiced every single day. As a result, I improved a lot.' },
      { text: "that's why", meaning: '그래서 ~한 것이다', example: "It only takes ten minutes from my house. That's why I go there so often." },
      { text: 'on the other hand', meaning: '반면에', example: 'Online shopping is convenient. On the other hand, you cannot try things on.' },
      { text: 'in the end', meaning: '결국', example: 'In the end, we managed to catch the last train home.' },
      { text: 'not to mention', meaning: '~은 말할 것도 없고', example: "The view was incredible, not to mention the food." },
    ],
  },
  {
    id: 'tasks',
    name: '상황별 표현',
    icon: '🎬',
    desc: '문항 유형별 필수 표현 — 묘사, 습관, 과거 경험, 롤플레이, 의견 말하기.',
    items: [
      { text: "It's located in the heart of the city.", meaning: '[묘사] 위치 설명', example: "My favorite cafe is located in the heart of the city." },
      { text: 'What I love most about it is...', meaning: '[묘사] 가장 좋은 점 강조', example: 'What I love most about it is the cozy atmosphere.' },
      { text: 'I make it a rule to...', meaning: '[습관] ~하는 것을 원칙으로 한다', example: 'I make it a rule to work out at least three times a week.' },
      { text: 'Whenever I get a chance, I...', meaning: '[습관] 기회가 될 때마다', example: 'Whenever I get a chance, I go jogging along the river.' },
      { text: 'It happened out of the blue.', meaning: '[과거] 갑자기 일어났다', example: 'The power went out — it happened totally out of the blue.' },
      { text: 'I was about to..., when...', meaning: '[과거] 막 ~하려던 참에', example: 'I was about to leave the house when it started pouring.' },
      { text: "I'm calling to ask about...", meaning: '[롤플레이] 전화 용건 말하기', example: "Hi, I'm calling to ask about the movie schedule this weekend." },
      { text: 'I was wondering if...', meaning: '[롤플레이] 정중한 질문/요청', example: 'I was wondering if I could change my reservation to Sunday.' },
      { text: "I know it's not your fault, but...", meaning: '[문제해결] 부드럽게 항의 시작', example: "I know it's not your fault, but I really need this fixed today." },
      { text: 'Would it be possible to...?', meaning: '[문제해결] 대안 제시', example: 'Would it be possible to get a refund or exchange it?' },
      { text: 'From my point of view,...', meaning: '[의견] 내 관점에서는', example: 'From my point of view, technology has made our lives much easier.' },
      { text: 'I would say it depends on...', meaning: '[의견] ~에 따라 다르다', example: 'I would say it depends on how you use it.' },
    ],
  },
  {
    id: 'survey',
    name: '서베이 주제별',
    icon: '📋',
    desc: '서베이에서 고른 주제별 필수 표현. 내 주제 것만 골라 외워도 답변 퀄리티가 확 올라가요.',
    items: [
      { group: '🏠 집 · 사는 곳', text: 'a cozy two-bedroom apartment', meaning: '아늑한 방 두 개짜리 아파트', example: 'I live in a cozy two-bedroom apartment with my family.' },
      { group: '🏠 집 · 사는 곳', text: 'get a great view of', meaning: '~의 전망이 좋다', example: 'My room gets a great view of the Han River.' },
      { group: '🏠 집 · 사는 곳', text: 'feel right at home', meaning: '내 집처럼 편안하다', example: 'The moment I walk in, I feel right at home.' },
      { group: '🏠 집 · 사는 곳', text: "I've lived here my whole life.", meaning: '평생 여기 살았다', example: "I've lived here my whole life, so I know every corner of this area." },
      { group: '🏠 집 · 사는 곳', text: 'my go-to spot for relaxing', meaning: '쉴 때 즐겨 찾는 곳', example: 'My balcony is my go-to spot for relaxing after work.' },
      { group: '🏘️ 동네 · 이웃', text: 'a quiet residential area', meaning: '조용한 주택가', example: 'I live in a quiet residential area just outside the city.' },
      { group: '🏘️ 동네 · 이웃', text: 'within walking distance', meaning: '걸어갈 수 있는 거리에', example: "There's a big park within walking distance of my house." },
      { group: '🏘️ 동네 · 이웃', text: 'have easy access to', meaning: '~을 편리하게 이용할 수 있다', example: 'We have easy access to the subway and tons of restaurants.' },
      { group: '🏘️ 동네 · 이웃', text: 'get along well with my neighbors', meaning: '이웃과 잘 지내다', example: 'I get along really well with my next-door neighbors.' },
      { group: '🏘️ 동네 · 이웃', text: 'a strong sense of community', meaning: '끈끈한 공동체 의식', example: 'Our neighborhood has a strong sense of community.' },
      { group: '🎬 영화', text: 'a huge fan of', meaning: '~의 열렬한 팬', example: "I'm a huge fan of action movies with great special effects." },
      { group: '🎬 영화', text: 'keep me on the edge of my seat', meaning: '손에 땀을 쥐게 하다', example: 'The movie kept me on the edge of my seat the whole time.' },
      { group: '🎬 영화', text: 'the plot twist blew my mind', meaning: '반전이 충격적이었다', example: 'The plot twist at the end totally blew my mind.' },
      { group: '🎬 영화', text: 'worth watching twice', meaning: '두 번 볼 가치가 있는', example: "It's definitely worth watching twice — you catch new details." },
      { group: '🎤 공연 · 콘서트', text: 'catch a live show', meaning: '라이브 공연을 보다', example: 'I try to catch a live show at least once a month.' },
      { group: '🎤 공연 · 콘서트', text: 'the atmosphere was electric', meaning: '분위기가 후끈 달아올랐다', example: 'The atmosphere was electric when the band came on stage.' },
      { group: '🎤 공연 · 콘서트', text: 'sing along to', meaning: '(노래를) 따라 부르다', example: 'Everyone was singing along to every single song.' },
      { group: '🎤 공연 · 콘서트', text: 'front-row seats', meaning: '맨 앞줄 좌석', example: 'We were lucky enough to get front-row seats.' },
      { group: '🎤 공연 · 콘서트', text: 'give me goosebumps', meaning: '소름 돋게 하다', example: 'Hearing that song live gave me goosebumps.' },
      { group: '🎤 공연 · 콘서트', text: 'book tickets in advance', meaning: '티켓을 미리 예매하다', example: 'You have to book tickets months in advance these days.' },
      { group: '🎵 음악', text: 'suit my taste', meaning: '내 취향에 맞다', example: 'Calm acoustic songs really suit my taste.' },
      { group: '🎵 음악', text: 'put me in a good mood', meaning: '기분 좋게 만들다', example: 'Upbeat songs always put me in a good mood.' },
      { group: '🎵 음악', text: 'have it on repeat', meaning: '무한 반복 재생하다', example: "I've had that song on repeat all week." },
      { group: '🎵 음악', text: 'the lyrics really speak to me', meaning: '가사가 마음에 와닿다', example: 'The lyrics really speak to me, especially when I feel down.' },
      { group: '🌳 공원', text: 'take a stroll', meaning: '한가롭게 산책하다', example: 'I like to take a stroll along the trail after dinner.' },
      { group: '🌳 공원', text: 'get some fresh air', meaning: '바람을 쐬다', example: 'I go to the park to get some fresh air and clear my head.' },
      { group: '🌳 공원', text: 'packed with people', meaning: '사람들로 붐비는', example: 'On weekends, the park is packed with families and joggers.' },
      { group: '🌳 공원', text: 'a great escape from the city', meaning: '도심 속 탈출구', example: 'The park is a great escape from the hustle and bustle of the city.' },
      { group: '🏖️ 해변', text: 'soak up the sun', meaning: '햇살을 만끽하다', example: 'We spent the whole afternoon soaking up the sun.' },
      { group: '🏖️ 해변', text: 'dip my feet in the water', meaning: '물에 발을 담그다', example: 'I rolled up my pants and dipped my feet in the water.' },
      { group: '🏖️ 해변', text: 'the sound of the waves', meaning: '파도 소리', example: 'The sound of the waves is so calming to me.' },
      { group: '🏖️ 해변', text: 'walk along the shore', meaning: '해안가를 따라 걷다', example: 'We walked along the shore barefoot at sunset.' },
      { group: '✈️ 여행', text: 'off the beaten path', meaning: '잘 알려지지 않은 (여행지)', example: 'We visited some small towns off the beaten path.' },
      { group: '✈️ 여행', text: 'immerse myself in the local culture', meaning: '현지 문화에 푹 빠지다', example: 'I try to immerse myself in the local culture when I travel.' },
      { group: '✈️ 여행', text: 'travel light', meaning: '짐을 가볍게 싸다', example: 'I always try to travel light — just one backpack.' },
      { group: '✈️ 여행', text: 'a once-in-a-lifetime experience', meaning: '일생일대의 경험', example: 'Watching the sunrise there was a once-in-a-lifetime experience.' },
      { group: '☕ 카페', text: 'a regular at', meaning: '~의 단골이다', example: "I'm a regular at the cafe near my office." },
      { group: '☕ 카페', text: 'freshly brewed coffee', meaning: '갓 내린 커피', example: 'Nothing beats the smell of freshly brewed coffee.' },
      { group: '☕ 카페', text: 'chill out with a cup of coffee', meaning: '커피 마시며 쉬다', example: 'I love chilling out with a cup of coffee on weekends.' },
      { group: '☕ 카페', text: 'people-watch', meaning: '사람 구경하다', example: 'I like to people-watch from the window seat.' },
      { group: '🏃 운동', text: 'work up a sweat', meaning: '땀을 쫙 빼다', example: 'I like to work up a sweat first thing in the morning.' },
      { group: '🏃 운동', text: 'stay in shape', meaning: '건강/몸매를 유지하다', example: 'I exercise three times a week to stay in shape.' },
      { group: '🏃 운동', text: 'warm up / cool down', meaning: '준비운동 / 정리운동', example: 'I always warm up before running and cool down after.' },
      { group: '🏃 운동', text: 'feel refreshed', meaning: '개운하다', example: 'I feel so refreshed after a good workout.' },
      { group: '🛍️ 쇼핑', text: 'window shopping', meaning: '아이쇼핑', example: "I enjoy window shopping even when I'm not buying anything." },
      { group: '🛍️ 쇼핑', text: 'get a great deal', meaning: '아주 싸게 사다', example: 'I got a great deal on these shoes — half off!' },
      { group: '🛍️ 쇼핑', text: "couldn't resist", meaning: '(사고 싶어서) 참을 수 없었다', example: "It was on sale, so I couldn't resist buying it." },
      { group: '🛍️ 쇼핑', text: 'cut down on impulse buying', meaning: '충동구매를 줄이다', example: "I'm trying to cut down on impulse buying these days." },
      { group: '🛍️ 쇼핑', text: 'try things on', meaning: '(옷을) 입어보다', example: 'I like to try things on before I buy them.' },
    ],
  },
  {
    id: 'vocab',
    name: '고득점 어휘',
    icon: '💎',
    desc: '네이티브가 일상에서 쓰는 콜로케이션·관용구. 한 문장에 하나씩만 넣어도 레벨이 달라져요.',
    items: [
      { text: 'hit the gym', meaning: '헬스장에 가다', example: 'I usually hit the gym right after work.' },
      { text: 'grab a bite', meaning: '간단히 먹다', example: 'We grabbed a bite before the movie started.' },
      { text: 'catch up with friends', meaning: '친구들과 회포를 풀다', example: 'I love catching up with friends over coffee.' },
      { text: 'take my mind off things', meaning: '잡생각을 떨치다', example: 'Jogging really helps me take my mind off things.' },
      { text: 'recharge my batteries', meaning: '재충전하다', example: 'I go camping once a month to recharge my batteries.' },
      { text: "it's a hassle", meaning: '번거로운 일이다', example: "Returning things online is such a hassle." },
      { text: 'worth every penny', meaning: '돈값을 하다', example: 'The trip was expensive, but it was worth every penny.' },
      { text: 'once in a blue moon', meaning: '아주 가끔', example: 'I only eat fast food once in a blue moon.' },
      { text: 'be swamped with work', meaning: '일에 파묻히다', example: 'I was swamped with work last week, so I could not exercise.' },
      { text: "can't get enough of", meaning: '아무리 해도 질리지 않는다', example: "I can't get enough of that band's new album." },
      { text: 'a hidden gem', meaning: '숨은 명소', example: 'That little restaurant is a hidden gem in my neighborhood.' },
      { text: 'lift my spirits', meaning: '기분을 북돋우다', example: 'Listening to upbeat music always lifts my spirits.' },
    ],
  },
];
