// 학습 자료: 만능 문장, 필러, 연결어, 상황별 표현, 고득점 어휘
const STUDY_SECTIONS = [
  {
    id: 'universal',
    name: '만능 문장',
    icon: '🪄',
    desc: '어떤 질문에도 쓸 수 있는 문장들. 시간 벌기 → 본론 → 마무리 흐름을 만들어줘요.',
    items: [
      { text: "That's a really interesting question.", meaning: '시간 벌기 (질문 직후)', example: "Oh, that's a really interesting question. Let me think." },
      { text: 'Well, let me think about that for a second.', meaning: '생각할 시간 벌기', example: "Hmm, well, let me think about that for a second... Okay, so..." },
      { text: 'Oh, where do I even start?', meaning: '할 말이 많다는 뉘앙스로 시작', example: "My favorite movie? Oh, where do I even start?" },
      { text: "It's hard to pick just one, but if I had to choose...", meaning: '하나 고르기 어려울 때', example: "It's hard to pick just one, but if I had to choose, I'd say my trip to Jeju." },
      { text: "To be honest, I've never really thought about that before.", meaning: '돌발 질문 대처', example: "To be honest, I've never really thought about that before, but I guess..." },
      { text: 'If I remember correctly, it was about two years ago.', meaning: '과거 경험 시작', example: 'If I remember correctly, it was about two years ago, in the summer.' },
      { text: 'Looking back on it now, it was such a great experience.', meaning: '경험 회상 마무리', example: 'Looking back on it now, it was such a great experience for me.' },
      { text: "What I'm trying to say is...", meaning: '말이 꼬였을 때 정리', example: "What I'm trying to say is, it totally changed how I see things." },
      { text: "All in all, that's why I really enjoy it.", meaning: '이유 설명 마무리', example: "All in all, that's why I really enjoy going there every weekend." },
      { text: "So yeah, that's pretty much it.", meaning: '자연스러운 답변 마무리', example: "So yeah, that's pretty much it. That's my typical weekend." },
    ],
  },
  {
    id: 'fillers',
    name: '필러 · 담화표지',
    icon: '🧩',
    desc: '침묵 대신 자연스럽게 채우는 말들. 남발하지 말고 문장 사이사이에 양념처럼!',
    items: [
      { text: 'you know', meaning: '있잖아요 (공감 유도)', example: "It was, you know, one of those days when everything goes wrong." },
      { text: 'actually', meaning: '사실은 (정보 수정·강조)', example: "Actually, I didn't like coffee at first." },
      { text: 'I mean', meaning: '그러니까 내 말은 (부연)', example: "It was huge. I mean, it took us an hour to walk around it." },
      { text: 'kind of / sort of', meaning: '약간, 어느 정도 (완화)', example: "I was kind of nervous at first, but it turned out fine." },
      { text: 'well', meaning: '음, 글쎄 (뜸들이기)', example: "Well, it depends on the situation, I guess." },
      { text: 'to be honest', meaning: '솔직히 말하면', example: "To be honest, I'm not a big fan of horror movies." },
      { text: 'the thing is', meaning: '문제는, 중요한 건', example: "I wanted to go, but the thing is, I had no time at all." },
      { text: 'as far as I know', meaning: '내가 알기로는', example: "As far as I know, it's the oldest cafe in my neighborhood." },
      { text: 'believe it or not', meaning: '믿기 힘들겠지만', example: "Believe it or not, I've watched that movie more than ten times." },
      { text: 'if that makes sense', meaning: '무슨 말인지 아시겠죠? (마무리)', example: "It's busy but relaxing at the same time, if that makes sense." },
    ],
  },
  {
    id: 'connectors',
    name: '연결어',
    icon: '🔗',
    desc: '문장과 문장을 잇는 다리. 스토리에 흐름과 논리를 만들어줘요.',
    items: [
      { text: 'first of all', meaning: '우선, 먼저', example: 'First of all, the location is perfect for me.' },
      { text: 'on top of that', meaning: '게다가 (추가)', example: "The food was amazing, and on top of that, the staff were super friendly." },
      { text: 'speaking of which', meaning: '말이 나온 김에', example: "Speaking of which, I actually went there again last weekend." },
      { text: 'meanwhile', meaning: '그러는 동안', example: 'I was waiting in line. Meanwhile, my friend was looking for seats.' },
      { text: 'whereas', meaning: '~인 반면 (비교)', example: 'My hometown is quiet, whereas Seoul is always crowded and busy.' },
      { text: 'even though', meaning: '~임에도 불구하고', example: 'Even though it was raining, we decided to go hiking anyway.' },
      { text: 'as a result', meaning: '그 결과', example: 'I practiced every single day. As a result, I improved a lot.' },
      { text: "that's why", meaning: '그래서 ~한 것이다', example: "It only takes ten minutes from my house. That's why I go there so often." },
      { text: 'on the other hand', meaning: '반면에', example: 'Online shopping is convenient. On the other hand, you cannot try things on.' },
      { text: 'in the end', meaning: '결국', example: 'In the end, we managed to catch the last train home.' },
      { text: 'not to mention', meaning: '~은 말할 것도 없고', example: "The view was incredible, not to mention the food." },
    ],
  },
  {
    id: 'tasks',
    name: '상황별 표현',
    icon: '🎬',
    desc: '문항 유형별 필수 표현 — 묘사, 습관, 과거 경험, 롤플레이, 의견 말하기.',
    items: [
      { text: "It's located in the heart of the city.", meaning: '[묘사] 위치 설명', example: "My favorite cafe is located in the heart of the city." },
      { text: 'What I love most about it is...', meaning: '[묘사] 가장 좋은 점 강조', example: 'What I love most about it is the cozy atmosphere.' },
      { text: 'I make it a rule to...', meaning: '[습관] ~하는 것을 원칙으로 한다', example: 'I make it a rule to work out at least three times a week.' },
      { text: 'Whenever I get a chance, I...', meaning: '[습관] 기회가 될 때마다', example: 'Whenever I get a chance, I go jogging along the river.' },
      { text: 'It happened out of the blue.', meaning: '[과거] 갑자기 일어났다', example: 'The power went out — it happened totally out of the blue.' },
      { text: 'I was about to..., when...', meaning: '[과거] 막 ~하려던 참에', example: 'I was about to leave the house when it started pouring.' },
      { text: "I'm calling to ask about...", meaning: '[롤플레이] 전화 용건 말하기', example: "Hi, I'm calling to ask about the movie schedule this weekend." },
      { text: 'I was wondering if...', meaning: '[롤플레이] 정중한 질문/요청', example: 'I was wondering if I could change my reservation to Sunday.' },
      { text: "I know it's not your fault, but...", meaning: '[문제해결] 부드럽게 항의 시작', example: "I know it's not your fault, but I really need this fixed today." },
      { text: 'Would it be possible to...?', meaning: '[문제해결] 대안 제시', example: 'Would it be possible to get a refund or exchange it?' },
      { text: 'From my point of view,...', meaning: '[의견] 내 관점에서는', example: 'From my point of view, technology has made our lives much easier.' },
      { text: 'I would say it depends on...', meaning: '[의견] ~에 따라 다르다', example: 'I would say it depends on how you use it.' },
    ],
  },
  {
    id: 'vocab',
    name: '고득점 어휘',
    icon: '💎',
    desc: '네이티브가 일상에서 쓰는 콜로케이션·관용구. 한 문장에 하나씩만 넣어도 레벨이 달라져요.',
    items: [
      { text: 'hit the gym', meaning: '헬스장에 가다', example: 'I usually hit the gym right after work.' },
      { text: 'grab a bite', meaning: '간단히 먹다', example: 'We grabbed a bite before the movie started.' },
      { text: 'catch up with friends', meaning: '친구들과 회포를 풀다', example: 'I love catching up with friends over coffee.' },
      { text: 'take my mind off things', meaning: '잡생각을 떨치다', example: 'Jogging really helps me take my mind off things.' },
      { text: 'recharge my batteries', meaning: '재충전하다', example: 'I go camping once a month to recharge my batteries.' },
      { text: "it's a hassle", meaning: '번거로운 일이다', example: "Returning things online is such a hassle." },
      { text: 'worth every penny', meaning: '돈값을 하다', example: 'The trip was expensive, but it was worth every penny.' },
      { text: 'once in a blue moon', meaning: '아주 가끔', example: 'I only eat fast food once in a blue moon.' },
      { text: 'be swamped with work', meaning: '일에 파묻히다', example: 'I was swamped with work last week, so I could not exercise.' },
      { text: "can't get enough of", meaning: '아무리 해도 질리지 않는다', example: "I can't get enough of that band's new album." },
      { text: 'a hidden gem', meaning: '숨은 명소', example: 'That little restaurant is a hidden gem in my neighborhood.' },
      { text: 'lift my spirits', meaning: '기분을 북돋우다', example: 'Listening to upbeat music always lifts my spirits.' },
    ],
  },
];
